// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmQhxcgHjK5NmKk6TdAoWFegUUplanb0',
    appId: '1:776825087706:web:fd47b2b8343e32c1ada7e3',
    messagingSenderId: '776825087706',
    projectId: 'dojo-challenge-app',
    authDomain: 'dojo-challenge-app.firebaseapp.com',
    storageBucket: 'dojo-challenge-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFKNbOKEBA75PvEm9L6xbagIkPYv1eNYg',
    appId: '1:776825087706:android:f6f3e0a77d617448ada7e3',
    messagingSenderId: '776825087706',
    projectId: 'dojo-challenge-app',
    storageBucket: 'dojo-challenge-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKlXVoFN2sZAs3Dj6fU_zay47hM8fO60',
    appId: '1:776825087706:ios:626127e14ae4b078ada7e3',
    messagingSenderId: '776825087706',
    projectId: 'dojo-challenge-app',
    storageBucket: 'dojo-challenge-app.firebasestorage.app',
    iosBundleId: 'com.example.dojoChallengeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTKlXVoFN2sZAs3Dj6fU_zay47hM8fO60',
    appId: '1:776825087706:ios:626127e14ae4b078ada7e3',
    messagingSenderId: '776825087706',
    projectId: 'dojo-challenge-app',
    storageBucket: 'dojo-challenge-app.firebasestorage.app',
    iosBundleId: 'com.example.dojoChallengeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApmQhxcgHjK5NmKk6TdAoWFegUUplanb0',
    appId: '1:776825087706:web:d00a10a459935d24ada7e3',
    messagingSenderId: '776825087706',
    projectId: 'dojo-challenge-app',
    authDomain: 'dojo-challenge-app.firebaseapp.com',
    storageBucket: 'dojo-challenge-app.firebasestorage.app',
  );
}
